# Generated by Django 4.2 on 2023-04-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_conversacion_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='autor',
        ),
    ]
