# Generated by Django 4.2 on 2023-04-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0004_remove_conversacion_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='texto',
            new_name='mensaje',
        ),
    ]
